package net.perfectdreams.dreamfight.utils

import java.util.*

object RandomTeamName {
    var rtn = ArrayList<String>()

    init {
        rtn.add("Pastel")
        rtn.add("Pão")
        rtn.add("Coxinha")
        rtn.add("Tails")
        rtn.add("Asriel")
        rtn.add("Sonic")
        rtn.add("Mario")
        rtn.add("Luigi")
        rtn.add("Yoshi")
        rtn.add("Arroz")
        rtn.add("Feijão")
        rtn.add("Batata")
        rtn.add("Pobres")
        rtn.add("Ricos")
        rtn.add("Biscoito")
        rtn.add("Bolacha")
        rtn.add("Fondue")
        rtn.add("Panda")
        rtn.add("Dreamer")
        rtn.add("Beliebers")
        rtn.add("Carvalho")
        rtn.add("Baiano")
        rtn.add("Paulista")
        rtn.add("Santos")
        rtn.add("Palmeiras")
        rtn.add("Corinthians")
        rtn.add("Vikings")
        rtn.add("Power")
        rtn.add("Bárbaros")
        rtn.add("Clash")
        rtn.add("Thor")
        rtn.add("Matin")
        rtn.add("Matinho")
        rtn.add("Matinhu")
        rtn.add("Amazonas")
        rtn.add("Banana")
        rtn.add("Pudim")
        rtn.add("Facebook")
        rtn.add("Twitter")
        rtn.add("Toddynho")
        rtn.add("Dolly")
        rtn.add("Requeijão")
        rtn.add("Manteiga")
        rtn.add("Margarina")
        rtn.add("Bolo")
        rtn.add("Sparkly")
        rtn.add("Comida")
        rtn.add("PowerRangers")
        rtn.add("Indefinido")
        rtn.add("Gold")
        rtn.add("Rainbow")
        rtn.add("Fundilho")
        rtn.add("Bunda")
        rtn.add("Esponja")
        rtn.add("PvP")
        rtn.add("Loritta")
        rtn.add("Pantufa")
        rtn.add("Gabriela")
        rtn.add("Jerbs")
        rtn.add("Discord")
        rtn.add("Pollux")
    }
}